/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_temon_serial_internal_serialport_SerialPort */

#ifndef _Included_com_temon_serial_internal_serialport_SerialPort
#define _Included_com_temon_serial_internal_serialport_SerialPort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_temon_serial_internal_serialport_SerialPort
 * Method:    open
 * Signature: (Ljava/lang/String;IIIIIII)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_com_temon_serial_internal_serialport_SerialPort_open
        (JNIEnv *, jclass, jstring, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_temon_serial_internal_serialport_SerialPort
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_temon_serial_internal_serialport_SerialPort_close
        (JNIEnv *, jobject);

/*
 * Class:     com_temon_serial_internal_serialport_SerialPort
 * Method:    isDeviceOnline
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_temon_serial_internal_serialport_SerialPort_isDeviceOnline
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
